# This is a basic workflow to help you get started with Actions

name: Netlify Deploy

# Trigger on push to master
# Trigger everyday at 2 UTC (for scheduled posts)
on:
  push:
    branches: [master]
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Node.js'
        uses: actions/setup-node@v1.4.2
        with:
          version: 12.x

      - name: 'Build Site'
        run: |
          yarn install --production
          yarn build

      - name: 'Deploy to Netlify'
        uses: nwtgck/actions-netlify@v1.0
        with:
          publish-dir: './public'
          production-branch: master
          deploy-message: '${{ github.event.head_commit.message }}'
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
